package es.cifpcm.forvagos.pojos;
// Generated 20-ene-2017 13:02:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,catalog="forvagos"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="id_usuario"), @UniqueConstraint(columnNames="nif_nie")} 
)
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nombre;
     private String apellidos;
     private String nifNie;
     private String nacionalidad;
     private String email;
     private String telefonoFijo;
     private String telefonoMovil;
     private int idUsuario;
     private Set<Reservas> reservases = new HashSet<Reservas>(0);

    public Cliente() {
    }

	
    public Cliente(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Cliente(String nombre, String apellidos, String nifNie, String nacionalidad, String email, String telefonoFijo, String telefonoMovil, int idUsuario, Set<Reservas> reservases) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.nifNie = nifNie;
       this.nacionalidad = nacionalidad;
       this.email = email;
       this.telefonoFijo = telefonoFijo;
       this.telefonoMovil = telefonoMovil;
       this.idUsuario = idUsuario;
       this.reservases = reservases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cliente", nullable=false)
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellidos", length=100)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="nif_nie", unique=true, length=10)
    public String getNifNie() {
        return this.nifNie;
    }
    
    public void setNifNie(String nifNie) {
        this.nifNie = nifNie;
    }

    
    @Column(name="nacionalidad", length=100)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    
    @Column(name="email", unique=true, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telefono_fijo", length=12)
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }

    
    @Column(name="telefono_movil", length=12)
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }
    
    public void setTelefonoMovil(String telefonoMovil) {
        this.telefonoMovil = telefonoMovil;
    }

    
    @Column(name="id_usuario", unique=true, nullable=false)
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set<Reservas> getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set<Reservas> reservases) {
        this.reservases = reservases;
    }




}


