package es.cifpcm.forvagos.pojos;
// Generated 20-ene-2017 13:02:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name="grupo"
    ,catalog="forvagos"
)
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private Boolean admin;
     private Boolean manager;
     private Boolean clientes;
     private Set<UsuarioGrupo> usuarioGrupos = new HashSet<UsuarioGrupo>(0);

    public Grupo() {
    }

    public Grupo(Boolean admin, Boolean manager, Boolean clientes, Set<UsuarioGrupo> usuarioGrupos) {
       this.admin = admin;
       this.manager = manager;
       this.clientes = clientes;
       this.usuarioGrupos = usuarioGrupos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_grupo", nullable=false)
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }

    
    @Column(name="admin")
    public Boolean getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    
    @Column(name="manager")
    public Boolean getManager() {
        return this.manager;
    }
    
    public void setManager(Boolean manager) {
        this.manager = manager;
    }

    
    @Column(name="clientes")
    public Boolean getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Boolean clientes) {
        this.clientes = clientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupo")
    public Set<UsuarioGrupo> getUsuarioGrupos() {
        return this.usuarioGrupos;
    }
    
    public void setUsuarioGrupos(Set<UsuarioGrupo> usuarioGrupos) {
        this.usuarioGrupos = usuarioGrupos;
    }




}


