package es.cifpcm.forvagos.pojos;
// Generated 20-ene-2017 13:02:30 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * HotelServicios generated by hbm2java
 */
@Entity
@Table(name="hotel_servicios"
    ,catalog="forvagos"
    , uniqueConstraints = {@UniqueConstraint(columnNames="id_hotel"), @UniqueConstraint(columnNames="id_servicio")} 
)
public class HotelServicios  implements java.io.Serializable {


     private Integer idHotelServicio;
     private Hotel hotel;
     private Servicio servicio;

    public HotelServicios() {
    }

    public HotelServicios(Hotel hotel, Servicio servicio) {
       this.hotel = hotel;
       this.servicio = servicio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_hotel_servicio", nullable=false)
    public Integer getIdHotelServicio() {
        return this.idHotelServicio;
    }
    
    public void setIdHotelServicio(Integer idHotelServicio) {
        this.idHotelServicio = idHotelServicio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_hotel", unique=true)
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_servicio", unique=true)
    public Servicio getServicio() {
        return this.servicio;
    }
    
    public void setServicio(Servicio servicio) {
        this.servicio = servicio;
    }




}


