package es.cifpcm.forvagos.pojos;
// Generated 20-ene-2017 13:02:30 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name="hotel"
    ,catalog="forvagos"
)
public class Hotel  implements java.io.Serializable {


     private Integer idHotel;
     private Municipios municipios;
     private String nombre;
     private String telefono;
     private String fax;
     private String cp;
     private Short categoria;
     private String email;
     private BigDecimal precioBase;
     private Set<Temporada> temporadas = new HashSet<Temporada>(0);
     private Set<Reservas> reservases = new HashSet<Reservas>(0);
     private Set<HotelServicios> hotelServicioses = new HashSet<HotelServicios>(0);

    public Hotel() {
    }

	
    public Hotel(Municipios municipios, String nombre) {
        this.municipios = municipios;
        this.nombre = nombre;
    }
    public Hotel(Municipios municipios, String nombre, String telefono, String fax, String cp, Short categoria, String email, BigDecimal precioBase, Set<Temporada> temporadas, Set<Reservas> reservases, Set<HotelServicios> hotelServicioses) {
       this.municipios = municipios;
       this.nombre = nombre;
       this.telefono = telefono;
       this.fax = fax;
       this.cp = cp;
       this.categoria = categoria;
       this.email = email;
       this.precioBase = precioBase;
       this.temporadas = temporadas;
       this.reservases = reservases;
       this.hotelServicioses = hotelServicioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_hotel", nullable=false)
    public Integer getIdHotel() {
        return this.idHotel;
    }
    
    public void setIdHotel(Integer idHotel) {
        this.idHotel = idHotel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_municipio", nullable=false)
    public Municipios getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Municipios municipios) {
        this.municipios = municipios;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="telefono", length=9)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="fax", length=9)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="CP", length=5)
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }

    
    @Column(name="categoria")
    public Short getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Short categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="precio_base", precision=10)
    public BigDecimal getPrecioBase() {
        return this.precioBase;
    }
    
    public void setPrecioBase(BigDecimal precioBase) {
        this.precioBase = precioBase;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hotel")
    public Set<Temporada> getTemporadas() {
        return this.temporadas;
    }
    
    public void setTemporadas(Set<Temporada> temporadas) {
        this.temporadas = temporadas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hotel")
    public Set<Reservas> getReservases() {
        return this.reservases;
    }
    
    public void setReservases(Set<Reservas> reservases) {
        this.reservases = reservases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hotel")
    public Set<HotelServicios> getHotelServicioses() {
        return this.hotelServicioses;
    }
    
    public void setHotelServicioses(Set<HotelServicios> hotelServicioses) {
        this.hotelServicioses = hotelServicioses;
    }




}


