package es.cifpcm.forvagos.pojos;
// Generated 20-ene-2017 13:02:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipios generated by hbm2java
 */
@Entity
@Table(name="municipios"
    ,catalog="forvagos"
)
public class Municipios  implements java.io.Serializable {


     private Short idMunicipio;
     private Provincias provincias;
     private int codMunicipio;
     private int dc;
     private String nombre;
     private Set<Hotel> hotels = new HashSet<Hotel>(0);

    public Municipios() {
    }

	
    public Municipios(Provincias provincias, int codMunicipio, int dc, String nombre) {
        this.provincias = provincias;
        this.codMunicipio = codMunicipio;
        this.dc = dc;
        this.nombre = nombre;
    }
    public Municipios(Provincias provincias, int codMunicipio, int dc, String nombre, Set<Hotel> hotels) {
       this.provincias = provincias;
       this.codMunicipio = codMunicipio;
       this.dc = dc;
       this.nombre = nombre;
       this.hotels = hotels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_municipio", nullable=false)
    public Short getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Short idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_provincia", nullable=false)
    public Provincias getProvincias() {
        return this.provincias;
    }
    
    public void setProvincias(Provincias provincias) {
        this.provincias = provincias;
    }

    
    @Column(name="cod_municipio", nullable=false)
    public int getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(int codMunicipio) {
        this.codMunicipio = codMunicipio;
    }

    
    @Column(name="DC", nullable=false)
    public int getDc() {
        return this.dc;
    }
    
    public void setDc(int dc) {
        this.dc = dc;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="municipios")
    public Set<Hotel> getHotels() {
        return this.hotels;
    }
    
    public void setHotels(Set<Hotel> hotels) {
        this.hotels = hotels;
    }




}


