package es.cifpcm.forvagos.pojos;
// Generated 20-ene-2017 13:02:30 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Reservas generated by hbm2java
 */
@Entity
@Table(name="reservas"
    ,catalog="forvagos"
    , uniqueConstraints = {@UniqueConstraint(columnNames="fecha_init"), @UniqueConstraint(columnNames="id_cliente"), @UniqueConstraint(columnNames="id_hotel")} 
)
public class Reservas  implements java.io.Serializable {


     private Integer idReserva;
     private Cliente cliente;
     private Hotel hotel;
     private Date fechaInit;
     private Date fechaFin;
     private BigDecimal precioTotal;

    public Reservas() {
    }

	
    public Reservas(Cliente cliente, Hotel hotel, Date fechaInit, Date fechaFin) {
        this.cliente = cliente;
        this.hotel = hotel;
        this.fechaInit = fechaInit;
        this.fechaFin = fechaFin;
    }
    public Reservas(Cliente cliente, Hotel hotel, Date fechaInit, Date fechaFin, BigDecimal precioTotal) {
       this.cliente = cliente;
       this.hotel = hotel;
       this.fechaInit = fechaInit;
       this.fechaFin = fechaFin;
       this.precioTotal = precioTotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_reserva", nullable=false)
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente", unique=true, nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_hotel", unique=true, nullable=false)
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_init", unique=true, nullable=false, length=10)
    public Date getFechaInit() {
        return this.fechaInit;
    }
    
    public void setFechaInit(Date fechaInit) {
        this.fechaInit = fechaInit;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", nullable=false, length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="precioTotal", precision=10)
    public BigDecimal getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(BigDecimal precioTotal) {
        this.precioTotal = precioTotal;
    }




}


