package es.cifpcm.forvagos.pojos;
// Generated 20-ene-2017 13:02:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servicio generated by hbm2java
 */
@Entity
@Table(name="servicio"
    ,catalog="forvagos"
)
public class Servicio  implements java.io.Serializable {


     private int idServicio;
     private String nombre;
     private Set<HotelServicios> hotelServicioses = new HashSet<HotelServicios>(0);

    public Servicio() {
    }

	
    public Servicio(int idServicio) {
        this.idServicio = idServicio;
    }
    public Servicio(int idServicio, String nombre, Set<HotelServicios> hotelServicioses) {
       this.idServicio = idServicio;
       this.nombre = nombre;
       this.hotelServicioses = hotelServicioses;
    }
   
     @Id 

    
    @Column(name="id_servicio", nullable=false)
    public int getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(int idServicio) {
        this.idServicio = idServicio;
    }

    
    @Column(name="nombre", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="servicio")
    public Set<HotelServicios> getHotelServicioses() {
        return this.hotelServicioses;
    }
    
    public void setHotelServicioses(Set<HotelServicios> hotelServicioses) {
        this.hotelServicioses = hotelServicioses;
    }




}


