package es.cifpcm.forvagos.pojos;
// Generated 20-ene-2017 13:02:30 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Temporada generated by hbm2java
 */
@Entity
@Table(name="temporada"
    ,catalog="forvagos"
    , uniqueConstraints = @UniqueConstraint(columnNames="id_hotel") 
)
public class Temporada  implements java.io.Serializable {


     private Integer idTemporada;
     private Hotel hotel;
     private Boolean temporadaAlta;
     private Date fechaInicio;
     private Date fechaFin;
     private Short modDescuentoIncremento;

    public Temporada() {
    }

    public Temporada(Hotel hotel, Boolean temporadaAlta, Date fechaInicio, Date fechaFin, Short modDescuentoIncremento) {
       this.hotel = hotel;
       this.temporadaAlta = temporadaAlta;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.modDescuentoIncremento = modDescuentoIncremento;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_Temporada", nullable=false)
    public Integer getIdTemporada() {
        return this.idTemporada;
    }
    
    public void setIdTemporada(Integer idTemporada) {
        this.idTemporada = idTemporada;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_hotel", unique=true)
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }

    
    @Column(name="temporada_alta")
    public Boolean getTemporadaAlta() {
        return this.temporadaAlta;
    }
    
    public void setTemporadaAlta(Boolean temporadaAlta) {
        this.temporadaAlta = temporadaAlta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="Mod_descuento_incremento")
    public Short getModDescuentoIncremento() {
        return this.modDescuentoIncremento;
    }
    
    public void setModDescuentoIncremento(Short modDescuentoIncremento) {
        this.modDescuentoIncremento = modDescuentoIncremento;
    }




}


