package es.cifpcm.forvagos.pojos;
// Generated 20-ene-2017 13:02:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="forvagos"
    , uniqueConstraints = {@UniqueConstraint(columnNames="id_cliente"), @UniqueConstraint(columnNames="login")} 
)
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String login;
     private String contraseña;
     private int idCliente;
     private Set<UsuarioGrupo> usuarioGrupos = new HashSet<UsuarioGrupo>(0);

    public Usuario() {
    }

	
    public Usuario(String login, String contraseña, int idCliente) {
        this.login = login;
        this.contraseña = contraseña;
        this.idCliente = idCliente;
    }
    public Usuario(String login, String contraseña, int idCliente, Set<UsuarioGrupo> usuarioGrupos) {
       this.login = login;
       this.contraseña = contraseña;
       this.idCliente = idCliente;
       this.usuarioGrupos = usuarioGrupos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario", nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="login", unique=true, nullable=false, length=30)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="contraseña", nullable=false, length=50)
    public String getContraseña() {
        return this.contraseña;
    }
    
    public void setContraseña(String contraseña) {
        this.contraseña = contraseña;
    }

    
    @Column(name="id_cliente", unique=true, nullable=false)
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<UsuarioGrupo> getUsuarioGrupos() {
        return this.usuarioGrupos;
    }
    
    public void setUsuarioGrupos(Set<UsuarioGrupo> usuarioGrupos) {
        this.usuarioGrupos = usuarioGrupos;
    }




}


