package es.cifpcm.forvagos.pojos;
// Generated 20-ene-2017 13:02:30 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioGrupo generated by hbm2java
 */
@Entity
@Table(name="usuario_grupo"
    ,catalog="forvagos"
)
public class UsuarioGrupo  implements java.io.Serializable {


     private Integer idUsuarioGrupo;
     private Grupo grupo;
     private Usuario usuario;

    public UsuarioGrupo() {
    }

    public UsuarioGrupo(Grupo grupo, Usuario usuario) {
       this.grupo = grupo;
       this.usuario = usuario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_usuario_grupo", nullable=false)
    public Integer getIdUsuarioGrupo() {
        return this.idUsuarioGrupo;
    }
    
    public void setIdUsuarioGrupo(Integer idUsuarioGrupo) {
        this.idUsuarioGrupo = idUsuarioGrupo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_grupo", nullable=false)
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


